= WildFly NoSQL 
:toc:

== Introduction
The goal of wildfly-nosql, is no-nonsense improvements focused on making the developer’s
life easier when using NoSQL on https://github.com/wildfly/wildfly +
https://github.com/wildfly-swarm/wildfly-swarm.
In particular, not to hide and abstract the underlying NoSQL APIs but to give
simple and natural access to them. The configuration allows NoSQL database connection profiles to be defined, to be used by applications. The CDI access simplifies application access to the defined NoSQL database connection profiles.

=== Connection pooling
Connections to NoSQL database servers are managed by the underlying native NoSQL drivers.
Connection pooling is provided directly by the native NoSQL drivers.

== Define NoSQL connection profiles

Each NoSQL connection profile uniquely names the profile *id*, which can be used to *@Inject @Named("id")*
the connection into your application code.  
[source,java]
----
   @Inject @Named("MyMongoDB") MongoDatabase database;
   @Inject @Named("MyCassandra") Cluster cluster;
   @Inject @Named("MyOrientDBPool") OPartitionedDatabasePool pool;
   @Inject @Named("MyNeo4j") Driver database;
----

Each NoSQL connection uniquely names the JNDI lookup *jndi-name*, which can be easily used by
application code.
[source,java]
----
   @Resource(lookup = "java:jboss/cassandra/MyDB")  Cluster cluster;
   @Resource(lookup = "java:jboss/mongodb/MyDB") MongoDatabase database;
   @Resource(lookup = "java:jboss/neo4j/MyDB") Driver database;
   @Resource(lookup = "java:jboss/orientdb/MyDB")  OPartitionedDatabasePool pool;
----

=== WildFly
Each defined connection profile, is shared by all applications deployed to the
WildFly application server.

=== WildFly Swarm
WildFly Swarm has one deployment per app server instance, therefore, the defined
connection profiles are only used by application deployment.

You get to bring your own NoSQL driver. In fact, you must bring your own NoSQL driver.
All that’s required though is just adding it as a normal Maven dependency to your project (
check the below Java driver version table to make sure it will work).

[source,xml]
----
  <dependencies>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>mongodb</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongo-java-driver</artifactId>
      <version>${version.mongodb.driver}</version>
    </dependency>
  </dependencies>
----

[source,xml]
----
 <dependencies>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>cassandra</artifactId>
    </dependency>
    <dependency>
      <groupId>com.datastax.cassandra</groupId>
      <artifactId>cassandra-driver-core</artifactId>
      <version>${version.cassandra.driver}</version>
    </dependency>
  </dependencies>
----


[source,xml]
----
 <dependencies>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>neo4j</artifactId>
 </dependency>
    <dependency>
      <groupId>org.neo4j.driver</groupId>
      <artifactId>neo4j-java-driver</artifactId>
      <version>${version.neo4j.driver}</version>
    </dependency>
 </dependencies>
----


[source,xml]
----
    <dependencies>
        <dependency>
            <groupId>org.wildfly.swarm</groupId>
            <artifactId>orientdb</artifactId>
        </dependency>

        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-graphdb</artifactId>
        </dependency>

        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-object</artifactId>
        </dependency>

        <dependency>
            <groupId>com.orientechnologies</groupId>
            <artifactId>orientdb-client</artifactId>
        </dependency>

        <dependency>
            <groupId>com.tinkerpop.blueprints</groupId>
            <artifactId>blueprints-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.googlecode.concurrentlinkedhashmap</groupId>
            <artifactId>concurrentlinkedhashmap-lru</artifactId>
        </dependency>
----

=== MongoDB Java driver versions

.MongoDB Java driver (org.mongodb:mongo-java-driver).
|===
|  Version  |  WildFly  |  WildFly Swarm

|3.0.3
|NO
|YES

|3.2.2
|YES
|YES

|3.3.0
|NO
|YES

|3.4.2
|NO
|YES

|===


=== Connecting to MongoDB from WildFly

The *mongodb* subsystem may define multiple MongoDB connection profiles, that are used to obtain com.mongodb.MongoClient +
com.mongodb.client.MongoDatabase class instances that represent each defined profile.  The MongoClient/MongoDatabase classes
are thread safe and can be shared by multiple deployed applications.  If the defined profiles are updated
while deployed applications are using them, the applications will be restarted.

https://github.com/wildfly/wildfly-nosql/blob/master/mongodb/subsystem/src/main/resources/schema/wildfly-mongodb_1_0.xsd[MongoDB subsystem syntax]

[source,xml]
----
<!-- example of WildFly MongoDB client subsystem defining two profiles. -->
<subsystem xmlns="urn:jboss:domain:mongodb:1.0">
    <mongo name="default" id="mongodbtestprofile" jndi-name="java:jboss/mongodb/test" database="mongotestdb" security-domain="mongoRealm" auth-type="DEFAULT" ssl="false" >
        <host name="default" outbound-socket-binding-ref="mongotesthost"/>
        <properties name="default">
            <property name="writeConcern" value="ACKNOWLEDGED"/>
            <property name="readConcern" value="LOCAL"/>
        </properties>
    </mongo>
    <mongo name="default2" id="mongodbsales" jndi-name="java:jboss/mongodb/sales" database="mongotestdb" security-domain="mongoRealm" auth-type="DEFAULT" ssl="false" >
        <host name="default2" outbound-socket-binding-ref="mongotesthost"/>
    </mongo>
</subsystem>
----
=== Connecting to MongoDB from WildFly Swarm

Refer to Wildfly Swarm documentation for org.wildfly.swarm.mongodb.MongoDBFraction

Minimal example:
[source,java]
----
// Main.java
package org.wildflynosql.demo.rest;

import java.util.HashMap;

import org.wildfly.swarm.Swarm;
import org.wildfly.swarm.config.mongodb.Mongo;
import org.wildfly.swarm.config.mongodb.mongo.Host;
import org.wildfly.swarm.config.security.Flag;
import org.wildfly.swarm.config.security.SecurityDomain;
import org.wildfly.swarm.config.security.security_domain.ClassicAuthentication;
import org.wildfly.swarm.config.security.security_domain.authentication.LoginModule;
import org.wildfly.swarm.mongodb.MongoDBFraction;
import org.wildfly.swarm.security.SecurityFraction;
import org.wildfly.swarm.spi.api.OutboundSocketBinding;

public class Main {

    public static void main(String... args) throws Exception {
        Swarm swarm = new Swarm(args)
            .outboundSocketBinding("standard-sockets",
                new OutboundSocketBinding("mongotesthost")
                    .remoteHost("localhost")
                    .remotePort(27017))
            .fraction(SecurityFraction.defaultSecurityFraction()
                .securityDomain(
                    new SecurityDomain("mongoRealm")
                        .classicAuthentication(
                            new ClassicAuthentication().loginModule(
                                new LoginModule("ConfiguredIdentity").code("ConfiguredIdentity")
                                    .flag(Flag.REQUIRED)
                                    .moduleOptions(new HashMap<Object, Object>() {
                                       {
                                           put("principal", "devuser");
                                           put("username", "devuser");
                                           put("password", "changethis");
                                       }
                                   }
                                )
                            )
                        )
                    )
                )
            .fraction(new MongoDBFraction()
                .mongo(new Mongo("mongodbtestprofile")
                    .host(new Host("mongotesthost")
                        .outboundSocketBindingRef("mongotesthost")
                        )
                    .database("mongotestdb")
                    .jndiName("java:jboss/mongodb/test")
                    .id("mongodbtestprofile")
                    .securityDomain("mongoRealm")
                        // .authType(Mongo.AuthType.GSSAPI)
                        // .authType(Mongo.AuthType.PLAIN_SASL)
                        // .authType(Mongo.AuthType.SCRAM_SHA_1)
                        // .authType(Mongo.AuthType.MONGODB_CR)
                        // .authType(Mongo.AuthType.MONGODB_X509)
                        .authType(Mongo.AuthType.DEFAULT)
                        .ssl(false)
                    )
            ).fraction(new org.wildfly.swarm.ee.EEFraction())
            .start()
            .deploy();
    }
}

----

[source,java]
----
// HelloWorldEndpoint.java
package org.wildflynosql.demo.rest;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;

import com.mongodb.client.MongoDatabase;

@ApplicationScoped
@Path("/hello")
public class HelloWorldEndpoint {

    @Inject @Named("mongodbtestprofile")
    MongoDatabase database;

    @GET
    @Produces("text/plain")
    public Response doGet() {
        return Response.ok("Hello from WildFly Swarm! database = " + database).build();
    }
}
----
[source,xml]
----
<!-- pom.xml -->
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.wildflynosql</groupId>
  <artifactId>demo</artifactId>
  <name>WildFly Swarm Example</name>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>war</packaging>

  <properties>
    <version.wildfly.swarm>2017.6.0-SNAPSHOT</version.wildfly.swarm>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <failOnMissingWebXml>false</failOnMissingWebXml>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <version.mongodb.driver>3.2.2</version.mongodb.driver>
    <version.org.glassfish.javax.json>1.0.3</version.org.glassfish.javax.json>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.wildfly.swarm</groupId>
        <artifactId>bom-all</artifactId>
        <version>${version.wildfly.swarm}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <finalName>demo</finalName>
    <plugins>
      <plugin>
        <groupId>org.wildfly.swarm</groupId>
        <artifactId>wildfly-swarm-plugin</artifactId>
        <version>${version.wildfly.swarm}</version>
        <configuration>
          <mainClass>org.wildflynosql.demo.rest.Main</mainClass>
        </configuration>

        <executions>
          <execution>
            <goals>
              <goal>package</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <!-- Java EE 7 dependency -->
    <dependency>
      <groupId>javax</groupId>
      <artifactId>javaee-api</artifactId>
      <version>7.0</version>
      <scope>provided</scope>
    </dependency>
    <!-- WildFly Swarm Fractions -->
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jaxrs-jsonp</artifactId>
    </dependency>

    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>jsonp</artifactId>
    </dependency>

    <dependency>
      <groupId>org.glassfish</groupId>
      <artifactId>javax.json</artifactId>
      <version>${version.org.glassfish.javax.json}</version>
    </dependency>
    <dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>mongodb</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongo-java-driver</artifactId>
      <version>${version.mongodb.driver}</version>
    </dependency>

  </dependencies>
</project>
----

[source,xml]
----
<!-- empty beans.xml -->
<beans xmlns="http://java.sun.com/xml/ns/javaee"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="
      http://java.sun.com/xml/ns/javaee
      http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">
</beans>
----


=== Cassandra Java driver versions

.Cassandra Java driver (com.datastax.cassandra:cassandra-driver-core).
|===
|  Version  |  WildFly  |  WildFly Swarm

|3.0.0
|NO
|YES

|===

=== Connecting to Cassandra from WildFly

=== Connecting to Cassandra from WildFly Swarm

=== Connecting to OrientDB from WildFly

=== Connecting to OrientDB from WildFly Swarm

=== Connecting to Neo4j from WildFly

=== Connecting to Neo4j from WildFly Swarm


== CDI Injection

== JNDI lookup

=== Logging categories

org.wildfly.nosql - Enable NoSQL subsystem logging.

org.wildfly.swarm.neo4j - Enable Neo4j fraction logging.

org.wildfly.swarm.orientdb - Enable OrientDB fraction logging.

org.wildfly.swarm.cassandra - Enable Cassandra fraction logging.

org.wildfly.swarm.mongodb - Enable MongoDB fraction logging.

=== Common issues
1. Incorrectly spelled profile name causes CDI injection or JNDI lookup, to fail.  Correct to use
correct spelling of NoSQL profile name.
2.  Missing beans.xml leads to deployment failure.

== Community

=== Issue tracking
Report issues via https://issues.jboss.org/browse/WFNOSQL.

=== Dicussion forum
Discussion forum is https://groups.google.com/d/forum/wildfly-nosql.

=== IRC chat
Also find us on freenode irc room #wildfly-nosql.

